### ISSUE TITLE
Meeting Topics: 11-17

### ISSUE THREAD

**Issue by alidursen** [swe-ms-boun/2018fall-swe574-g1#90]
This week's topics to discuss:
- [x] Weekly effort/comparison to project plan
- [x] Feedback on previous weeks IRL meeting / repo reconfiguration (see #85)
- [x] Update on sequence diagram? (see #80, #34)
- [x] Hot topic: google maps (see #67, #29)
- [x] Annotation technicality update? (see #87)
- [x] Closing of some old issues (see #6, #7, #70)
- [x] Further planning/projection

**Comment by alidursen** [comment]
Meeting notes can be found [here](/swe-ms-boun/2018fall-swe574-g1/wiki/1.1.-Meeting-Notes#2018-11-17).
